### ISSUE TITLE
I am very interested in your current work. I wonder if you can create a user guide that explains how to run your code on a device?

### ISSUE THREAD

**Issue by chenjinhua1993** [rand-chain/rust-randchain#118]
## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by SebastianElvis** [comment]
Thanks for the interest!

Due to the limited capacity of us, we haven't got a chance to deliver a production-level implementation or the user guide. In particular, the miner, DNS server and CLI haven't been finished yet. Sorry about that and we will try to finish the implementation as soon as possible.

Nevertheless, we do have a prototype on the `proto` branch https://github.com/rand-chain/rust-randchain/tree/proto, where mining is simulated and protocol parameters are loosely chosen. To start a small cluster locally, make use of https://github.com/rand-chain/rust-randchain/blob/proto/tools/docker-compose-4.yml. To start a cluster on AWS, make use of https://github.com/rand-chain/rust-randchain/blob/proto/evaluation/aws/main.sh. We don't have documentations on them yet, but we are happy to answer further questions on deploying the prototype version, docker and AWS usage.

**Comment by chenjinhua1993** [comment]
Thank you very much! i will try later
